In [1]:
import xarray as xr
import cftime 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import os
import time
import logging
import cartopy.crs as ccrs
import metpy  
import calendar
import argparse
import glob

In [2]:
run = 'parallel_new_input/'
os.chdir('/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_support_code/'+run)

print(os.getcwd())

/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_support_code/parallel_new_input

In [2]:
output_col_names = ['lon'
,'lat'
,'variable'
,'cohort_number'
,'stand_age'
,'potential_veg'
,'current_veg'
,'subtype'
,'community_type'
,'silt_clay'  ###check this order
,'lc_state'
,'land_area'
,'cohort_area'
,'year'
,'annual_sum'
,'monthly_maximum'
,'monthly_mean'
,'monthly_minimum'
,'Jan'
,'Feb'
,'Mar'
,'Apr'
,'May'
,'Jun'
,'Jul'
,'Aug'
,'Sep'
,'Oct'
,'Nov'
,'Dec'
,'region']

input_col_names = ["lon", 'lat','var' ,'Area', 'year', 'sum', 'max', 'average'
         , 'min', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'
         , 'Nov', 'Dec', 'Area_Name']

In [3]:
read_in_data = pd.read_csv('/home/smmrrr/TEM_Analysis/TEM_Analysis/Aggregate_TEM/all_parallel_variable_info.csv')

In [4]:
read_in_data

,input_group,NIRR,PAR,PREC,TAIR,VPR,WS10,output_paths,output_group,output_var
0,0,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,0,NPP
1,0,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,0,FCO2
2,0,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,0,SOILORGC
3,0,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,0,TEMP
4,0,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,0,FRDL
...,...,...,...,...,...,...,...,...,...,...
4995,9954,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,9954,FH2O
4996,9954,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,9954,SOILORGC
4997,9954,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,9954,NPP
4998,9954,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,9954,VEGINGPP
4999,9954,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,/home/smmrrr/TEM/TEM_Runs/TEM_parallel_run_sup...,9954,TEMP

In [5]:
i = 4

In [6]:
##read in precipitation files
prec = pd.read_csv(read_in_data.loc[i, 'PREC']
           , names = input_col_names)
par = pd.read_csv(read_in_data.loc[i, 'PAR']
           , names = input_col_names)
nirr = pd.read_csv(read_in_data.loc[i, 'NIRR']
           , names = input_col_names)
tair = pd.read_csv(read_in_data.loc[i, 'TAIR']
           , names = input_col_names)
vpr = pd.read_csv(read_in_data.loc[i, 'VPR']
           , names = input_col_names)
ws10 = pd.read_csv(read_in_data.loc[i, 'WS10']
           , names = input_col_names)


print('data read in')
## shape input datasets wide to long
prec = pd.melt(prec, id_vars = ['lon','lat', 'Area', 'year'], value_vars = [
'Jan',
'Feb',
'Mar',
'Apr',
'May',
'Jun',
'Jul',
'Aug',
'Sep',
'Oct',
'Nov',
'Dec'], 
         var_name='month', value_name='prec'
        ,col_level=0)

par = pd.melt(par, id_vars = ['lon','lat', 'Area', 'year'], value_vars = [
'Jan',
'Feb',
'Mar',
'Apr',
'May',
'Jun',
'Jul',
'Aug',
'Sep',
'Oct',
'Nov',
'Dec'], 
         var_name='month', value_name='par'
        ,col_level=0)

nirr = pd.melt(nirr, id_vars = ['lon','lat', 'Area', 'year'], value_vars = [
'Jan',
'Feb',
'Mar',
'Apr',
'May',
'Jun',
'Jul',
'Aug',
'Sep',
'Oct',
'Nov',
'Dec'], 
         var_name='month', value_name='nirr'
        ,col_level=0)

tair = pd.melt(tair, id_vars = ['lon','lat', 'Area', 'year'], value_vars = [
'Jan',
'Feb',
'Mar',
'Apr',
'May',
'Jun',
'Jul',
'Aug',
'Sep',
'Oct',
'Nov',
'Dec'], 
         var_name='month', value_name='tair'
        ,col_level=0)

vpr = pd.melt(vpr, id_vars = ['lon','lat', 'Area', 'year'], value_vars = [
'Jan',
'Feb',
'Mar',
'Apr',
'May',
'Jun',
'Jul',
'Aug',
'Sep',
'Oct',
'Nov',
'Dec'], 
         var_name='month', value_name='vpr'
        ,col_level=0)

ws10 = pd.melt(ws10, id_vars = ['lon','lat', 'Area', 'year'], value_vars = [
'Jan',
'Feb',
'Mar',
'Apr',
'May',
'Jun',
'Jul',
'Aug',
'Sep',
'Oct',
'Nov',
'Dec'], 
         var_name='month', value_name='ws10'
        ,col_level=0)

##merge climate variables together
climate_vars = prec.merge(
            par,on = ['lon','lat', 'Area', 'year', 'month']
            ).merge(
            tair ,on = ['lon','lat', 'Area', 'year', 'month']                           
            ).merge(
            nirr ,on = ['lon','lat', 'Area', 'year', 'month']                           
            ).merge(
            vpr ,on = ['lon','lat', 'Area', 'year', 'month']                           
            ).merge(
            ws10 ,on = ['lon','lat', 'Area', 'year', 'month']                           
            )

data read in

In [7]:
del prec, par, tair, nirr, vpr, ws10
##subset to forest veg types 
# cohort_output = cohort_output.loc[cohort_output['current_veg'].isin(forest_vegs)] 
print('clim processed')

clim processed

In [8]:
climate_vars
print('climate rows : '+ str(len(climate_vars)))

climate rows : 486864

In [9]:
###read in cohort output
cohort_output = pd.read_csv(read_in_data.loc[i, 'output_paths']
            , names = output_col_names)

print('cohort rows read in : '+ str(len(cohort_output)))

cohort rows read in : 41734

In [78]:
# cohort_output

In [10]:
###summary table of lat, lon, num years, num cohorts, 
summary_lon_lat = cohort_output.groupby(['lon', 'lat'])[['year']].nunique()
summary_lon_lat.to_csv('/home/smmrrr/TEM_output_processed/Aggregate_TEM/lon_lat_counts/'+read_in_data.loc[i, 'output_var']+str(read_in_data.loc[i, 'output_group'])+'.csv'
                        ,index = False)

In [11]:
##melt cohort output
cohort_output = pd.melt(cohort_output, id_vars = ['lon','lat', 'cohort_area', 'land_area', 'year','variable', 'current_veg', 'stand_age'], value_vars = [
'Jan',
'Feb',
'Mar',
'Apr',
'May',
'Jun',
'Jul',
'Aug',
'Sep',
'Oct',
'Nov',
'Dec'], 
         var_name='month', value_name='value'
        ,col_level=0)

print('cohort rows wide to long : '+ str(len(cohort_output)))

cohort rows wide to long : 500808

In [12]:
cohort_output

,lon,lat,cohort_area,land_area,year,variable,current_veg,stand_age,month,value
0,-180.0,65.0,1702,1039,84.9,FRDL,3,3,Jan,0.38
1,-180.0,65.0,1703,1039,82.7,FRDL,3,3,Jan,0.38
2,-180.0,65.0,1704,1039,44.5,FRDL,3,3,Jan,0.37
3,-180.0,65.0,1705,1039,77.9,FRDL,3,3,Jan,0.38
4,-180.0,65.0,1706,1039,90.0,FRDL,3,3,Jan,0.39
...,...,...,...,...,...,...,...,...,...,...
500803,-171.5,66.0,2018,1245,22.9,FRDL,2,2,Dec,Russia
500804,-171.5,66.0,2019,1245,24.3,FRDL,2,2,Dec,Russia
500805,-171.5,66.0,2020,1245,26.8,FRDL,2,2,Dec,Russia
500806,-171.5,66.0,2021,1245,19.4,FRDL,2,2,Dec,Russia
500807,-171.5,66.0,2022,1245,23.0,FRDL,2,2,Dec,Russia

In [14]:
#### match pfts to the current veg, bin by standage for forests
conditions = [
 cohort_output['current_veg'].isin([50, 49, 52, 53, 54, 55, 56]) 
    ,cohort_output['current_veg'].isin([51, 47])
, cohort_output['current_veg'].isin([48, 46]) 
    ,cohort_output['current_veg'].isin([4, 5, 6, 8, 9, 
                                        10, 11, 16, 17, 18, 19, 20, 25, 33])
    ,cohort_output['current_veg'].isin([7, 12, 13, 14, 22, 23, 24, 25, 26, 27, 28, 30, 31])
    ,cohort_output['current_veg'].isin([15, 35, 29])
    ,cohort_output['current_veg'].isin([2, 3])
    ,cohort_output['current_veg'].isin([21])
]

values = [
          'crop', 
          'pasture', 
          'urban or suburban', 
          'forest', 
          'grass', 
          'shrub', 
          'tundra',
            'desert']
cohort_output['pft'] = np.select(conditions, values, default = 'other')

# intervals_standage = [-1, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 125, 150, 3000]
# cohort_output['stand_age_bin'] = pd.cut(
#     cohort_output['stand_age'], bins=intervals_standage)
# # print(annual_current_veg[['pft', 'stand_age_bin']].value_counts())
# cohort_output.loc[cohort_output['pft']!='forest', ['stand_age_bin']] =  cohort_output['stand_age_bin'].min()
# cohort_output['stand_age_interval_min'] = cohort_output['stand_age_bin'].apply(lambda x: x.right).astype(int)

In [16]:
forest_vegs = [4, 5, 6, 8, 9, 10, 11, 16, 17, 18, 19, 20, 25, 33]
forest_types = ["Boreal Forest", "Forested Boreal Wetlands", "Boreal Woodlands","Mixed Temperate Forests", 
               "Temperate Coniferous Forests", "Temperate Deciduous Forests", "Temperate Forested Wetlands", 
               "Tropical Evergreen Forests", "Tropical Forested Wetlands", "Tropical Deciduous Forests", "Xeromorphic Forests and Woodlands"
               ,"Tropical Forested Floodplains", "Temperate Forested Floodplains", "Temperate Broadleaved Evergreen Forests"]

forest_pfts = pd.DataFrame({
'current_veg':forest_vegs, 
    'forest_type':forest_types
})

cohort_output=cohort_output.merge(forest_pfts, on = 'current_veg', how = 'left')

merged_dataset = cohort_output.merge(
            climate_vars, how = 'left'
    ,on = ['lon','lat', 'year', 'month']
            )

/home/smmrrr/miniconda3/envs/condaforge/lib/python3.10/site-packages/pandas/core/reshape/merge.py:1207: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  warnings.warn(

In [17]:
cohort_output

,lon,lat,cohort_area,land_area,year,variable,current_veg,stand_age,month,value,pft,forest_type
0,-180.0,65.0,1702,1039,84.9,FRDL,3,3,Jan,0.38,tundra,NaN
1,-180.0,65.0,1703,1039,82.7,FRDL,3,3,Jan,0.38,tundra,NaN
2,-180.0,65.0,1704,1039,44.5,FRDL,3,3,Jan,0.37,tundra,NaN
3,-180.0,65.0,1705,1039,77.9,FRDL,3,3,Jan,0.38,tundra,NaN
4,-180.0,65.0,1706,1039,90.0,FRDL,3,3,Jan,0.39,tundra,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
500803,-171.5,66.0,2018,1245,22.9,FRDL,2,2,Dec,Russia,tundra,NaN
500804,-171.5,66.0,2019,1245,24.3,FRDL,2,2,Dec,Russia,tundra,NaN
500805,-171.5,66.0,2020,1245,26.8,FRDL,2,2,Dec,Russia,tundra,NaN
500806,-171.5,66.0,2021,1245,19.4,FRDL,2,2,Dec,Russia,tundra,NaN
500807,-171.5,66.0,2022,1245,23.0,FRDL,2,2,Dec,Russia,tundra,NaN

In [15]:
cohort_output['temp_weight'] = cohort_output['value'] * cohort_output['cohort_area'] 


aggregations = {
 'cohort_area':'sum',
 'land_area':'sum',
 'value':'mean',
    'temp_weight':'sum'
}


cohort_output = cohort_output.groupby(
    ['lon','lat','variable','pft','current_veg','year','month' ,'stand_age_interval_min']
).agg(
aggregations
)


# all_grids =  all_grids.reset_index()

cohort_output['value_weight'] = cohort_output['temp_weight']/cohort_output['cohort_area']
cohort_output = cohort_output.reset_index()
print('cohort rows post cohort collapse : '+ str(len(cohort_output)))
# cohort_output

cohort rows post cohort collapse : 268944

In [17]:
merged_dataset.columns

Index(['lon', 'lat', 'variable', 'pft', 'current_veg', 'year', 'month',
       'stand_age_interval_min', 'cohort_area', 'land_area', 'value',
       'temp_weight', 'value_weight', 'forest_type', 'Area', 'prec', 'par',
       'tair', 'nirr', 'vpr', 'ws10'],
      dtype='object')

In [90]:
# lon_lat_pfts

merged_dataset.to_csv('/home/smmrrr/TEM_output_processed/first_checks_parallel/lon_lat_pfts/'+read_in_data.loc[i, 'output_var']+str(read_in_data.loc[i, 'output_group'])+'.csv'
                        ,index = False)

merged_dataset.loc[merged_dataset['pft']=='forest'].to_csv('/home/smmrrr/TEM_output_processed/first_checks_parallel/forest_lon_lat_pfts/'+read_in_data.loc[i, 'output_var']+str(read_in_data.loc[i, 'output_group'])+'.csv'
                        ,index = False)